import { create } from 'zustand'

/**
 * @description A star as represented in the application's UI layer. Mirrors the catalog
 * star shape but lives in the store so components that don't import the
 * catalog can still consume it.
 */
export interface Star {
  id: string
  name: string
  ra: number
  dec: number
  magnitude: number
  colorIndex: number
  hasAnomaly: boolean
  anomalyScore: number
}

/**
 * @description One detected anomaly (dip) extracted from a light curve, projected into the
 * minimal shape the UI cares about. Generated by `detectDips()` and stored
 * alongside the parent star id.
 */
export interface Anomaly {
  starId: string
  score: number
  depth: number
  duration: number
  asymmetry: number
  peakTime: number
  label: 'NORMAL' | 'NOTABLE' | 'INTERESTING' | 'WOW'
}

/**
 * @description Human-readable provenance labels for the panel's per-dip
 * citation line. Mirrors `LightcurveProvenance` in `anomalyDetector.ts`.
 */
export interface LightcurveProvenance {
  sourceName: string
  mission: string
  dataType: string
}

/**
 * @description Time-series flux samples plus the anomalies detected within them. Times are
 * in BKJD (Barycentric Kepler Julian Date), flux is normalized to ~1.0.
 * `source` distinguishes real MAST data, the explicit "data unavailable"
 * state (real fetch failed; we did NOT substitute fake data), and the
 * synthetic dev-only stand-in. When source is `'unavailable'` the arrays
 * are empty and the UI must not plot a chart.
 */
export interface LightcurveData {
  times: number[]
  flux: number[]
  dips: Anomaly[]
  source: 'real' | 'unavailable' | 'synthetic'
  provenance: LightcurveProvenance
}

/**
 * @description A request to fly the camera toward a celestial coordinate. The monotonic
 * `id` ensures the camera controller reacts even if two requests target the
 * exact same RA/Dec (e.g. clicking the same nav button twice).
 */
export interface FlyToCommand {
  ra: number
  dec: number
  // Monotonic id so the camera reacts even when target coords repeat
  id: number
}

interface AppState {
  selectedStar: Star | null
  hoveredStar: Star | null
  anomalies: Anomaly[]
  cameraTarget: { ra: number; dec: number }
  zoom: number
  mode: 'explore' | 'analyze' | 'report'
  lightcurve: LightcurveData | null
  /**
   * @description True while a `fetchLightcurve` call for the currently-selected
   * star is in flight. The panel uses this to show the progress bar instead
   * of stale data from the previously-selected star.
   */
  lightcurveLoading: boolean
  loading: boolean
  flyTo: FlyToCommand | null
  setSelectedStar: (star: Star | null) => void
  setHoveredStar: (star: Star | null) => void
  setAnomalies: (anomalies: Anomaly[]) => void
  setCameraTarget: (target: { ra: number; dec: number }) => void
  setZoom: (zoom: number) => void
  setMode: (mode: 'explore' | 'analyze' | 'report') => void
  setLightcurve: (data: LightcurveData | null) => void
  setLightcurveLoading: (loading: boolean) => void
  setLoading: (loading: boolean) => void
  requestFlyTo: (ra: number, dec: number) => void
}

let flyToCounter = 0

/**
 * @description Global Zustand store for the explorer.
 *
 * Setters are intentionally thin — components own their UI logic and only
 * push state transitions through the store. `requestFlyTo` is the one bit
 * of indirection: it bumps a monotonic id so the camera controller treats
 * each call as a fresh command.
 */
export const useStore = create<AppState>((set) => ({
  selectedStar: null,
  hoveredStar: null,
  anomalies: [],
  cameraTarget: { ra: 0, dec: 0 },
  zoom: 1,
  mode: 'explore',
  lightcurve: null,
  lightcurveLoading: false,
  loading: false,
  flyTo: null,
  setSelectedStar: (star) => set({ selectedStar: star }),
  setHoveredStar: (star) => set({ hoveredStar: star }),
  setAnomalies: (anomalies) => set({ anomalies }),
  setCameraTarget: (target) => set({ cameraTarget: target }),
  setZoom: (zoom) => set({ zoom }),
  setMode: (mode) => set({ mode }),
  setLightcurve: (data) => set({ lightcurve: data }),
  setLightcurveLoading: (loading) => set({ lightcurveLoading: loading }),
  setLoading: (loading) => set({ loading }),
  requestFlyTo: (ra, dec) => set({ flyTo: { ra, dec, id: ++flyToCounter } }),
}))
