import { create } from 'zustand'
import { FLAGGED_KEY, VISITED_KEY, loadIdSet, saveIdSet } from './persistence'
import type { CurveProfile, CurvePattern } from './curveClassifier'
import type { SimbadIdentity } from './simbadIds'

/**
 * @description Catalog of origin for a star. Used by the renderer to pick
 * a per-mission visual treatment (Kepler anomalies → red pulse, TESS
 * anomalies → cyan pulse). Optional because most catalog entries
 * (Hipparcos, synthetic fillers) don't come from a survey mission;
 * undefined means "no mission tag".
 */
export type StarSource = 'Kepler' | 'TESS' | 'Hipparcos'

/**
 * @description A star as represented in the application's UI layer. Mirrors the catalog
 * star shape but lives in the store so components that don't import the
 * catalog can still consume it.
 */
export interface Star {
  id: string
  name: string
  ra: number
  dec: number
  magnitude: number
  colorIndex: number
  hasAnomaly: boolean
  anomalyScore: number
  source?: StarSource
  /**
   * @description Kepler-field quadrant id (e.g. "C4") for anomaly stars
   * inside RA 290–305 / Dec 36–52. Assigned at merge time by
   * `quadrantFor` in `lib/quadrants.ts`. Undefined for stars outside
   * the grid (most TOI stars, off-field seeds, all Hipparcos fillers).
   */
  quadrant?: string
}

/**
 * @description One detected anomaly (dip) extracted from a light curve, projected into the
 * minimal shape the UI cares about. Generated by `detectDips()` and stored
 * alongside the parent star id.
 */
export interface Anomaly {
  starId: string
  score: number
  depth: number
  duration: number
  asymmetry: number
  peakTime: number
  label: 'NORMAL' | 'NOTABLE' | 'INTERESTING' | 'WOW'
}

/**
 * @description Human-readable provenance labels for the panel's per-dip
 * citation line. Mirrors `LightcurveProvenance` in `anomalyDetector.ts`.
 */
export interface LightcurveProvenance {
  sourceName: string
  mission: string
  dataType: string
}

/**
 * @description Time-series flux samples plus the anomalies detected within them. Times are
 * in BKJD (Barycentric Kepler Julian Date), flux is normalized to ~1.0.
 * `source` distinguishes real MAST data, the explicit "data unavailable"
 * state (real fetch failed; we did NOT substitute fake data), and the
 * synthetic dev-only stand-in. When source is `'unavailable'` the arrays
 * are empty and the UI must not plot a chart.
 */
export interface LightcurveData {
  times: number[]
  flux: number[]
  dips: Anomaly[]
  source: 'real' | 'unavailable' | 'synthetic'
  provenance: LightcurveProvenance
  /**
   * @description Descriptive measurements of the curve produced by
   * `classifyCurve`. Strictly measured features — does not assert a
   * physical cause. Null when the curve is unavailable (no data to
   * classify).
   */
  profile?: CurveProfile | null
  /**
   * @description Which mission archive actually served the data, or
   * null when the curve is synthetic / unavailable. Surfaced so the
   * UI can label the time axis correctly (BKJD for Kepler, TJD for
   * TESS) and pick mission-specific defaults like the gap threshold.
   */
  mission?: 'Kepler' | 'TESS' | null
  /**
   * @description Time gap (in days) above which two consecutive
   * samples should be treated as different observation runs (the
   * canvas line breaks across the gap rather than drawing a
   * diagonal stroke). Kepler quarters → 5; TESS sectors → 2. Falls
   * back to 5 when missing so existing behavior is preserved.
   */
  gapDays?: number
  /**
   * @description True when MAST served FEWER segments (quarters/sectors)
   * than its TAP listing said exist for the target — the curve is
   * incomplete. The UI must flag this loudly (a "PARTIAL N/M QUARTERS"
   * badge) so a label like SPARSE isn't read as a confident verdict on a
   * truncated curve. Undefined/false = complete.
   */
  partial?: boolean
  /**
   * @description Segment coverage: `recovered` of `expected` PDC segments
   * were successfully downloaded. Drives the "N/M" in the PARTIAL badge.
   * Undefined when not real MAST data.
   */
  segments?: { recovered: number; expected: number }
}

/**
 * @description A request to fly the camera toward a celestial coordinate. The monotonic
 * `id` ensures the camera controller reacts even if two requests target the
 * exact same RA/Dec (e.g. clicking the same nav button twice).
 */
export interface FlyToCommand {
  ra: number
  dec: number
  // Monotonic id so the camera reacts even when target coords repeat
  id: number
}

interface AppState {
  selectedStar: Star | null
  hoveredStar: Star | null
  anomalies: Anomaly[]
  cameraTarget: { ra: number; dec: number }
  zoom: number
  mode: 'explore' | 'analyze' | 'report'
  lightcurve: LightcurveData | null
  /**
   * @description True while a `fetchLightcurve` call for the currently-selected
   * star is in flight. The panel uses this to show the progress bar instead
   * of stale data from the previously-selected star.
   */
  lightcurveLoading: boolean
  /**
   * @description SIMBAD cross-identifier record for the currently-selected
   * star, or null when the star has no SIMBAD entry, the lookup failed, or
   * none has been fetched yet. Follows the `lightcurve` pattern (nullable
   * data + a sibling loading flag) rather than a discriminated union: the
   * panel treats miss / outage / not-yet-asked identically (render
   * nothing), so a richer state machine would buy no UI behavior.
   */
  identity: SimbadIdentity | null
  /**
   * @description True while a `fetchIdentity` call for the currently-
   * selected star is in flight. Distinguishes "still asking" from
   * "asked, nothing to show" so the panel can hold a slim placeholder
   * instead of popping the block in late. Cache hits resolve in a few
   * ms, so the panel gates the placeholder behind a short delay — see
   * `IDENTITY_PLACEHOLDER_DELAY_MS` in AnomalyPanel.
   */
  identityLoading: boolean
  /**
   * @description Every SIMBAD identity resolved this session, keyed by
   * app-form star id. Accumulates as the user selects stars; entries are
   * never evicted (a few hundred bytes each, bounded by how many stars
   * one session visits).
   *
   * This is the backing index for search-by-common-name (phase B3
   * mechanism (a)): once a star's identity has been resolved, its
   * common names become searchable for free, with no new SIMBAD query.
   * INSTANT coverage is therefore visited-stars-only BY DESIGN —
   * universal common-name search AS YOU TYPE would need a
   * per-keystroke SIMBAD query, which the B1 rate posture rules out.
   * Names for never-opened stars go through mechanism (b) instead
   * (the explicit press-Enter-to-ask escape hatch in `StarSearch`),
   * which writes its result back here via `indexIdentity` — so one
   * explicit ask permanently adds that name to this instant index.
   *
   * Stars confirmed ABSENT from SIMBAD are intentionally not recorded:
   * they contribute no searchable names, and the route already caches
   * the miss so re-selecting them costs no query.
   */
  resolvedIdentities: Map<string, SimbadIdentity>
  loading: boolean
  flyTo: FlyToCommand | null
  /**
   * @description Number of unique KOI (Kepler Object of Interest) stars
   * loaded from the NASA Exoplanet Archive. Drives the HUD anomaly
   * counter so it shows the global scientific count, not the per-star
   * dip count in `anomalies`. 0 while the KOI fetch is pending or if
   * it failed.
   */
  koiCount: number
  /**
   * @description Non-null when the KOI catalog fetch failed. The HUD can
   * surface this as a small "KOI catalog unavailable" tag so the user
   * understands why the anomaly count is 0.
   */
  koiError: string | null
  /**
   * @description Number of unique TOI (TESS Object of Interest) stars
   * loaded from the NASA Exoplanet Archive. Mirrors `koiCount` for the
   * TESS mission. 0 while the TOI fetch is pending or if it failed.
   */
  toiCount: number
  /**
   * @description Non-null when the TOI catalog fetch failed. Surfaced
   * in the HUD's TESS counter row the same way `koiError` is for KOI.
   */
  toiError: string | null
  /**
   * @description Subset of the merged catalog that has `hasAnomaly: true`,
   * pre-sorted by `anomalyScore` descending. Populated by `page.tsx`
   * after the KOI merge so HUD nav buttons ('GO TO NEAREST', 'NEXT
   * ANOMALY') can scan all KOIs cheaply without re-deriving on every
   * click. Empty array while KOI is still loading or if it failed.
   */
  anomalyStars: Star[]
  /**
   * @description Cursor into `anomalyStars` (already sorted by score
   * desc). The 'NEXT ANOMALY' button advances this; wraps to 0 at the
   * end. -1 = "haven't started cycling yet"; the first NEXT click
   * jumps to index 0 (the highest-scoring anomaly).
   */
  nextAnomalyCursor: number
  /**
   * @description Set of star ids the user has opened a light curve
   * for. Hydrated from localStorage `sae_visited` on mount and
   * persisted on every toggle. Drives the dimmed-pulse rendering for
   * already-seen anomalies in the 3D sky and the visited count in
   * the HUD progress bar.
   */
  visitedIds: Set<string>
  /**
   * @description Set of star ids the user has explicitly bookmarked
   * via the ★ button in the AnomalyPanel. Hydrated from localStorage
   * `sae_flagged`. Drives the white ring around flagged markers in
   * the 3D sky and the FLAGGED list panel in the HUD.
   */
  flaggedIds: Set<string>
  /**
   * @description Sky-radar cache: precomputed `CurvePattern` per star,
   * hydrated on mount from `/api/pattern-cache` (which reads the
   * shared server-side `pattern-cache.json`). Drives the extra
   * StarField overlay layer that tints markers by classification
   * result — IRREGULAR pops magenta, PERIODIC_UNIFORM fades to a dim
   * green, etc. Stars absent from this map render as usual.
   *
   * The lazy fill-in path (from selectStar) updates this Map AND
   * POSTs to `/api/pattern-cache` so organic exploration converges
   * with the batch job on the same shared cache.
   */
  classifiedPatterns: Map<string, CurvePattern>
  setSelectedStar: (star: Star | null) => void
  setHoveredStar: (star: Star | null) => void
  setAnomalies: (anomalies: Anomaly[]) => void
  setCameraTarget: (target: { ra: number; dec: number }) => void
  setZoom: (zoom: number) => void
  setMode: (mode: 'explore' | 'analyze' | 'report') => void
  setLightcurve: (data: LightcurveData | null) => void
  setLightcurveLoading: (loading: boolean) => void
  /**
   * @description Sets the selected star's identity. Passing a non-null
   * identity ALSO records it into `resolvedIdentities` under `starId`,
   * so the search index grows as a side effect of ordinary selection —
   * callers never maintain the two separately.
   * @param starId App-form id the identity was resolved for.
   * @param identity The resolved identity, or null for a miss/failure.
   */
  setIdentity: (starId: string, identity: SimbadIdentity | null) => void
  /**
   * @description Records an identity into the search index WITHOUT
   * touching the panel slot. Used when a lookup resolves after its
   * selection was superseded: the result can't be displayed (a newer
   * star owns the panel), but it is still a valid resolution of
   * `starId`, and the index is keyed by id so storing it cannot
   * mislabel the current selection.
   * @param starId App-form id the identity was resolved for.
   * @param identity The resolved identity.
   */
  indexIdentity: (starId: string, identity: SimbadIdentity) => void
  setIdentityLoading: (loading: boolean) => void
  setLoading: (loading: boolean) => void
  setKoiCount: (n: number) => void
  setKoiError: (err: string | null) => void
  setToiCount: (n: number) => void
  setToiError: (err: string | null) => void
  setAnomalyStars: (stars: Star[]) => void
  setNextAnomalyCursor: (i: number) => void
  requestFlyTo: (ra: number, dec: number) => void
  /**
   * @description Adds a star id to `visitedIds` (no-op if already
   * present) and persists the updated set to localStorage.
   */
  markVisited: (starId: string) => void
  /**
   * @description Toggles a star id's membership in `flaggedIds` and
   * persists the updated set to localStorage. Used by the bookmark
   * button in the AnomalyPanel.
   */
  toggleFlagged: (starId: string) => void
  /**
   * @description One-shot hydration from localStorage on app mount.
   * Called from a top-level useEffect; replaces the empty initial
   * sets with whatever the user persisted in previous sessions.
   */
  hydratePersistedSets: () => void
  /**
   * @description Replaces the classifiedPatterns map with a fresh
   * one. Called from `page.tsx` after fetching `/api/pattern-cache`
   * on mount. Also used by the batch-progress poller (if wired up
   * later) to periodically refresh the cache as new patterns land.
   */
  setClassifiedPatterns: (patterns: Map<string, CurvePattern>) => void
  /**
   * @description Records a single star's pattern into the map. Used by
   * the lazy fill-in path: after `selectStar` runs classifyCurve, the
   * result is dropped here so the sky-radar overlay picks it up
   * without another server round-trip. Creates a new Map instance so
   * React subscribers see a referential change.
   */
  setClassifiedPattern: (starId: string, pattern: CurvePattern) => void
}

let flyToCounter = 0

/**
 * @description Global Zustand store for the explorer.
 *
 * Setters are intentionally thin — components own their UI logic and only
 * push state transitions through the store. `requestFlyTo` is the one bit
 * of indirection: it bumps a monotonic id so the camera controller treats
 * each call as a fresh command.
 */
export const useStore = create<AppState>((set) => ({
  selectedStar: null,
  hoveredStar: null,
  anomalies: [],
  cameraTarget: { ra: 0, dec: 0 },
  zoom: 1,
  mode: 'explore',
  lightcurve: null,
  lightcurveLoading: false,
  identity: null,
  identityLoading: false,
  resolvedIdentities: new Map<string, SimbadIdentity>(),
  loading: false,
  flyTo: null,
  koiCount: 0,
  koiError: null,
  toiCount: 0,
  toiError: null,
  anomalyStars: [],
  nextAnomalyCursor: -1,
  // Sets start empty; the page calls hydratePersistedSets() once on
  // mount to replace these with the user's localStorage state. We
  // can't read localStorage at module-load time because Zustand's
  // create() runs on the server during SSR; reading there would
  // throw on `window`-less environments.
  visitedIds: new Set<string>(),
  flaggedIds: new Set<string>(),
  classifiedPatterns: new Map<string, CurvePattern>(),
  setSelectedStar: (star) => set({ selectedStar: star }),
  setHoveredStar: (star) => set({ hoveredStar: star }),
  setAnomalies: (anomalies) => set({ anomalies }),
  setCameraTarget: (target) => set({ cameraTarget: target }),
  setZoom: (zoom) => set({ zoom }),
  setMode: (mode) => set({ mode }),
  setLightcurve: (data) => set({ lightcurve: data }),
  setLightcurveLoading: (loading) => set({ lightcurveLoading: loading }),
  setIdentity: (starId, identity) => set(state => {
    // A miss/failure only clears the panel slot — nothing to index, and
    // no reason to churn the Map reference.
    if (!identity) return { identity: null }
    // Re-selecting a star already in the index: keep the existing Map
    // reference so search-index consumers don't recompute needlessly.
    if (state.resolvedIdentities.get(starId) === identity) return { identity }
    const next = new Map(state.resolvedIdentities)
    next.set(starId, identity)
    return { identity, resolvedIdentities: next }
  }),
  indexIdentity: (starId, identity) => set(state => {
    if (state.resolvedIdentities.get(starId) === identity) return state
    const next = new Map(state.resolvedIdentities)
    next.set(starId, identity)
    return { resolvedIdentities: next }
  }),
  setIdentityLoading: (loading) => set({ identityLoading: loading }),
  setLoading: (loading) => set({ loading }),
  setKoiCount: (n) => set({ koiCount: n }),
  setKoiError: (err) => set({ koiError: err }),
  setToiCount: (n) => set({ toiCount: n }),
  setToiError: (err) => set({ toiError: err }),
  setAnomalyStars: (stars) => set({ anomalyStars: stars, nextAnomalyCursor: -1 }),
  setNextAnomalyCursor: (i) => set({ nextAnomalyCursor: i }),
  requestFlyTo: (ra, dec) => set({ flyTo: { ra, dec, id: ++flyToCounter } }),
  markVisited: (starId) => set(state => {
    if (state.visitedIds.has(starId)) return state
    // New Set so React-subscribed components see a referential change
    const next = new Set(state.visitedIds)
    next.add(starId)
    saveIdSet(VISITED_KEY, next)
    return { visitedIds: next }
  }),
  toggleFlagged: (starId) => set(state => {
    const next = new Set(state.flaggedIds)
    if (next.has(starId)) next.delete(starId)
    else next.add(starId)
    saveIdSet(FLAGGED_KEY, next)
    return { flaggedIds: next }
  }),
  hydratePersistedSets: () => set({
    visitedIds: loadIdSet(VISITED_KEY),
    flaggedIds: loadIdSet(FLAGGED_KEY),
  }),
  setClassifiedPatterns: (patterns) => set({ classifiedPatterns: patterns }),
  setClassifiedPattern: (starId, pattern) => set(state => {
    if (state.classifiedPatterns.get(starId) === pattern) return state
    const next = new Map(state.classifiedPatterns)
    next.set(starId, pattern)
    return { classifiedPatterns: next }
  }),
}))
